const { contextBridge, ipcRenderer } = require('electron');
const channels = ['batch', 'select-batch', 'open-main', 'hide-tray', 'rescan-library', 'remove-photo', 'relink-photo', 'previous', 'dismiss-recovery', 'bootstrap', 'query', 'credential', 'connect', 'disconnect', 'import', 'favorite', 'playlist', 'settings', 'wallpaper', 'next', 'download', 'choose-download-directory', 'cache', 'clear-cache', 'open-link', 'update-status', 'check-update', 'install-update', 'open-downloaded-update', 'open-update', 'feedback', 'show-desktop', 'share', 'open-shared', 'import-shared'];
const api = Object.fromEntries(channels.map(name => [name.replace(/-([a-z])/g, (_, c) => c.toUpperCase()), data => ipcRenderer.invoke(`framewall:${name}`, data)]));
api.onUpdate = callback => { const listener = (_, value) => callback(value); ipcRenderer.on('framewall:update', listener); return () => ipcRenderer.removeListener('framewall:update', listener); };
api.onProgress = callback => { const listener = (_, value) => callback(value); ipcRenderer.on('framewall:progress', listener); return () => ipcRenderer.removeListener('framewall:progress', listener); };
api.onChanging = callback => { const listener = (_, value) => callback(value); ipcRenderer.on('framewall:changing', listener); return () => ipcRenderer.removeListener('framewall:changing', listener); };
api.onUpdater = callback => { const listener = (_, value) => callback(value); ipcRenderer.on('framewall:updater', listener); return () => ipcRenderer.removeListener('framewall:updater', listener); };
api.onBatch = callback => { const listener = (_, value) => callback(value); ipcRenderer.on('framewall:batch', listener); return () => ipcRenderer.removeListener('framewall:batch', listener); };
api.onNavigate = callback => { const listener = (_, value) => callback(value); ipcRenderer.on('framewall:navigate', listener); return () => ipcRenderer.removeListener('framewall:navigate', listener); };
contextBridge.exposeInMainWorld('framewall', api);
